### ISSUE TITLE
Consider renaming to FSharp.Text.RegexProvider

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Text.RegexProvider#11]
Hi @dtchepak 

I'm wondering if you might be able to rename this project to "FSharp.Text.RegexProvider"?  And likewise the provider would be in the namespace "FSharp.Text".

If you could I'd be immensely grateful.

(The reasons are somewhat obvious but are explained in the [recommended guidelines](http://fsharp.github.io/2014/09/19/fsharp-libraries.html) in more detail, would be happy to talk it over though!)

Best regards,
Don

**Comment by dtchepak** [comment]
Sure, happy to. Does this mean a new nuget package should be created too? (to replace [RegexProvider](https://www.nuget.org/packages/RegexProvider/))

**Comment by dsyme** [comment]
Yes that's right thanks

(nb. you don't remove the old one - nuget packages are never removed - just unlist it from the search index - follow the instructions under "Delete Package" on nuget.org).

**Comment by dtchepak** [comment]
* Renamed github repo to https://github.com/fsprojects/FSharp.Text.RegexProvider (old https://github.com/fsprojects/RegexProvider url redirects with 301)
* Pushed new nuget package: https://www.nuget.org/packages/FSharp.Text.RegexProvider
* Delisted old package: https://www.nuget.org/packages/RegexProvider/
* Updated DLL name to `FSharp.Text.RegexProvider`
* Updated namespace to `FSharp.Text.RegexProvider`
* Updated documentation website to: http://fsprojects.github.io/FSharp.Text.RegexProvider/

@dsyme, I think I've renamed everything. If you come across anything I've missed (or something I've messed up) please reopen the issue.
Cheers,
David

**Comment by dsyme** [comment]
Fantastic! Thanks!  BTW how did you get the 301 redirect on that URL?

**Comment by dtchepak** [comment]
Github did it automatically when I edited the project name. :-) The
gh-pages site didn't get a redirect though.

**Comment by dsyme** [comment]
Ah yes, that's what I meant - I thought you had said that http://fsprojects.github.io/RegexProvider/ got a redirect, but I see now that's not the case.  I wish GitHub would provide redirects for those too.
