### ISSUE TITLE
Unable to generate docs

### ISSUE THREAD

**Issue by dtchepak** [fsprojects/FSharp.Text.RegexProvider#12]
Missing code formatting on http://fsprojects.github.io/FSharp.Text.RegexProvider/

Running `build GenerateDocs` gave this error:

```
System.TypeInitializationException: The type initializer for 'Microsoft.FSharp.Metadata.AssemblyLoader' threw an exception. 
---> System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-PowerPack-Metadata>.$Metadata' threw an exception. 
---> System.ArgumentException: could not produce an FSharpAssembly object for the assembly 'FSharp.Core' because this is not an F# assembly
```

**Comment by dtchepak** [comment]
Hi @forki, @vasily-kirichenko. Any ideas on how to fix this?

And since I'm hassling you already, do either of you know how to get [the travis-ci build](https://travis-ci.org/fsprojects/FSharp.Text.RegexProvider) working again after moving this project to `FSharp.Text.RegexProvider`?

**Comment by sergey-tihon** [comment]
You should not copy `Fsharp.Core.dll` to target directory (`bin`).

**Comment by dtchepak** [comment]
Tried [setting `CopyLocal=False` for `FSharp.Core`](https://github.com/fsprojects/FSharp.Text.RegexProvider/blob/1077fed0d65f0004ad99e11226b3be8ae1a3c42a/src/RegexProvider/RegexProvider.fsproj#L47), but still get the same error.

**Comment by forki** [comment]
works for me

**Comment by dtchepak** [comment]
@forki, i've no idea why my setup isn't working. Could you please `build ReleaseDocs` to sort the website out while I try to work out what the problem is on my machine?

**Comment by forki** [comment]
let me convert to paket and update FSF ;-)

**Comment by forki** [comment]
https://github.com/fsprojects/FSharp.Text.RegexProvider/pull/13 <- worked for me and I was able to update the docs

**Comment by forki** [comment]
I take that back. somethign went wrong

**Comment by forki** [comment]
ok now it looks good

**Comment by dtchepak** [comment]
Works on my machine :tm: . Thanks a lot @forki!
