### ISSUE TITLE
Optionally change the names of the provided methods

### ISSUE THREAD

**Issue by pirrmann** [fsprojects/FSharp.Text.RegexProvider#15]
### Description

I'm trying to write code that can work on several regular expressions that share common groups. In order to do that I'm trying to use static constraints and inline methods to perform "duck-typing" on the provided types. This could work, but as methods names on provided types are the same that the ones in the Regex base class type, I then get a compiler error because the correct overload of the function can't be resolved.

I'd love to have the provided methods named `TypedMatch` and `TypedMatches` instead of `Match` and `Matches`. That way, the overload resolution problem cannot happen. In order to keep backward compatibility, that could be implemented using an optional `Prefix` parameter for the provider, that would change the names of the generated methods.

If the maintainers are ok with this idea in principle, I'll be pleased to do a pull-request.

**Comment by lasandell** [comment]
I ran into similar problems when trying to implement a typed `Replace` method for #7, so I named it `ReplaceTyped`. That PR seems to have gone by the wayside, though.

**Comment by vasily-kirichenko** [comment]
I'm OK with this.
