### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by Gabology** [fsprojects/FSharp.Text.RegexProvider#18]
As of now this TP is not compatible with .NET Core. It would be a very nice addition if it would be made compatible with this platform as well. How much work would it be making it compile to .NET Core currently?

**Comment by sergey-tihon** [comment]
It is definitely nice to have feature, but .NET Core is not ready for TPs as well as TPs are not ready for .NET Core. Read more here https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/80 & https://github.com/Microsoft/visualfsharp/issues/1496

**Comment by ChrisNikkel** [comment]
Looks like https://github.com/Microsoft/visualfsharp/issues/2406 is the open issue to track now.

**Comment by daz10000** [comment]
That issue (2406) is closed now.  It looks like you still need to apply the general type provider workaround but this should otherwise work for .netcore.  Would it be possible to put out a version?  The 4.6.1 version runs under netcore but you get an annoying message at compile and runtime.

**Comment by thinkbeforecoding** [comment]
Done with #24 , I just need someone to release the nuget 👍

**Comment by thinkbeforecoding** [comment]
Done by #24 
Nuget is here:
https://www.nuget.org/packages/FSharp.Text.RegexProvider/2.0.0
