### ISSUE TITLE
Support typed match with offset

### ISSUE THREAD

**Issue by realvictorprm** [fsprojects/FSharp.Text.RegexProvider#19]
Hello fellows,

It would improve the provider if typed match supports all overloads of the regular match function like specifying an offset.

If you're fine with this I would make a PR.

**Comment by dsyme** [comment]
Hi @realvictorprm - of course, improvements and updates would be very welcome

@dtchepak @forki @vasily-kirichenko - you're listed as maintainers on this repo. Would you like to continue that, and/or should we consider @realvictorprm as a co-maintainer?

@realvictorprm please send the PRs regardless - I'm sure that between us we'll review them :)

**Comment by vasily-kirichenko** [comment]
@dsyme why we should promote @realvictorprm to maintainers?..

**Comment by realvictorprm** [comment]
@vasily-kirichenko @dsyme I'm interested in this.

**Comment by dtchepak** [comment]
Hi @dsyme,  I'm happy to have a new maintainer. I do not have many opportunities to use this library anymore so it would be better if an active user were to make decisions on the project.

**Comment by dsyme** [comment]
@vasily-kirichenko My question was really whether the existing maintainers are happy continuing in that role.  For "fsprojects" projects the facilitators (curently @sergey-tihon and myself) may ask that from time to time to check on status.

@dtchepak Thanks for the update
