### ISSUE TITLE
Support option type for the typed match expression

### ISSUE THREAD

**Issue by realvictorprm** [fsprojects/FSharp.Text.RegexProvider#20]
Hello again :)

So far I understood the regex class it's safe to use the complete match and it's groups if the parent match field _Success_ is true. Moreover the same approach is used for active patterns and therefor I would like to add a _tryTypedMatch_ function to the provider having as additional fields the value of each group.

Would you appreciate this?

**Comment by dsyme** [comment]
@realvictorprm Sounds entirely reasonable

**Comment by thinkbeforecoding** [comment]
Fixed by #29 
will release the Nuget soon
