### ISSUE TITLE
Nuget page is missing metadata

### ISSUE THREAD

**Issue by pkese** [fsprojects/FSharp.Text.RegexProvider#26]
The corresponding page on Nuget ( https://www.nuget.org/packages/FSharp.Text.RegexProvider ) is missing links to the github project page and the documentation page ( http://fsprojects.github.io/FSharp.Text.RegexProvider/ )

**Comment by thinkbeforecoding** [comment]
I took the occasion to add a link to the license file, and changed all links to https.
For this I had to make some small changes on the doc files
