### ISSUE TITLE
Question: How do I set Regex options, e.g. RegexOptions.IgnoreCase ?

### ISSUE THREAD

**Issue by njlr** [fsprojects/FSharp.Text.RegexProvider#33]
How do I set Regex options, e.g. `RegexOptions.IgnoreCase`?

Perhaps this should be added to the docs?

**Comment by thinkbeforecoding** [comment]
You can specify the parameter in the options:
`
type MyRegex = RegexProvider<"...", options= RegexOptions.IgnoreCase >
`

You can also specify a timeout with the `matchTimeout` parameter.

**Comment by njlr** [comment]
Thanks for the pointer, although it doesn't seem to work: 

```fsharp
#r "nuget: FSharp.Text.RegexProvider,2.1.0"

open FSharp.Text

type MyRegex = RegexProvider.Regex< @"abc", options = RegexOptions.IgnoreCase >
// type MyRegex = RegexProvider.Regex< @"abc" > // Works, but not case-insensitive

let cases =
  [
    "abc"
    "ABC"
    "def"
  ]

for case in cases do
  printfn "%s %b" case (MyRegex.TypedIsMatch case)

```

> error FS3082: No static parameter exists with name 'options'

**Comment by thinkbeforecoding** [comment]
Ah ok...  right.
You have to pass them in a constructor:

`


#r "nuget: FSharp.Text.RegexProvider,2.1.0"

open FSharp.Text
open System.Text.RegularExpressions

type MyRegex = RegexProvider.Regex< @"abc" >
// type MyRegex = RegexProvider.Regex< @"abc" > // Works, but not case-insensitive
let rx = MyRegex(RegexOptions.IgnoreCase)

let cases =
  [
    "abc"
    "ABC"
    "def"
  ]

for case in cases do
  printfn "%s %b" case (rx.IsMatch case)
`

**Comment by njlr** [comment]
Thanks, that works.
